### ISSUE TITLE
Configure local USB camera

### ISSUE THREAD

**Issue by robmarkcole** [dcmartin/hassio-addons#1]
Hi @dcmartin 
I'm attempting to configure a USB camera as [described in this article](https://www.hackster.io/robin-cole/motion-activated-image-capture-and-classification-of-birds-6ef1ce), but am not sure of the config required. I recevied the following error:
```
not a valid value for dictionary value @ data['options']. Got ...'cameras': [{'name': 'usb', 'device': '/dev/video0'}]}
```
Cheers

**Comment by qLag** [comment]
I have the same problem. Even default configuration is invalid :/

**Comment by qLag** [comment]
Up. 
Can you help us please ? 

I get always this error when i update / save configu( even with default configuration / empty json objet etc ...)

![image](https://user-images.githubusercontent.com/3404563/45586147-ed242c00-b8f1-11e8-9178-4a7528441662.png)

**Comment by dcmartin** [comment]
Sorry; I was not paying attention!  I fixed that problem and will push an update; I apologize!

**Comment by dcmartin** [comment]
Per the example above, the "username" and "password" fields need to be set for controlled access to the motion capabilities made available for both control as well as live video.

**Comment by dcmartin** [comment]
Okay; fixed as of 0.3.120; dropped requirement for username and password (now default to empty strings); should work OOTB with PS3 eye camera attached; only output available in Web GUI through the "Data" link (listing of captured files).

**Comment by qLag** [comment]
Great ! It works, a lot of thanks !

**Comment by danielbenzvi** [comment]
I'm seeing the same issue now...
