### ISSUE TITLE
[BUG] Motion Classic: Failed to save addon

### ISSUE THREAD

**Issue by cskiwi** [dcmartin/hassio-addons#11]
Trying to save the addon gives an error (even the default configuration)

`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'log_level': 'info', 'default': {'username': '!secret motioncam-username', 'password': '!secret motioncam-password', 'netcam_userpass': '!secret netcam-userpass'}, 'mqtt': {'host': '!secret mqtt-broker', 'port': '!secret mqtt-port', 'username': '!secret mqtt-username', 'password': '!secret mqtt-password'}, 'group': '!secret motion-group', 'device': '!secret motion-device', 'client': '!secret motion-client', 'timezone': '!secret ha-timezone', 'cameras': [{'name': 'local', 'type': 'local', 'ic...`

Addon: Motion Classic
Version: 0.10.99

**Comment by necton** [comment]
Same problem (try on the RPI B+ and Odroid B2+). An attempt to change at least something in the config file results in an error (write-protected?).

Addon: Motion Classic
Version:  0.10.99
HA version: Home Assistant 2021.1.5

**Comment by necton** [comment]
I was delighted, reinstalled - the same result, bug not resolved...

**Comment by necton** [comment]
Uninstal>Host Restart>Install new 0.10.102 - problem not resolved. Config protected

Odroid N2+, Home Assistant OS 5.10, supervisor-2021.01.7, core-2021.1.5
