### ISSUE TITLE
unable to install motion addon via hassio

### ISSUE THREAD

**Issue by White-Goblin** [dcmartin/hassio-addons#2]
I'm unsure if this is my install, or this repository is incorrectly configured, but I'm not able to install motion on hassio. I'm fully up to date on the version.

Relevent logs from the hassio console:
`
19-05-20 09:31:07 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/cb7b3237/hello/config.json: required key not provided @ data['arch']. Got None
19-05-20 09:31:07 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/cb7b3237/intu/config.json: required key not provided @ data['arch']. Got None
19-05-20 09:31:07 INFO (MainThread) [hassio.store] Load add-ons from store: 66 all - 0 new - 0 remove
19-05-20 13:42:30 INFO (SyncWorker_13) [hassio.docker.addon] Start build cb7b3237/armv7-addon-motion:0.5.20
19-05-20 13:42:37 ERROR (SyncWorker_13) [hassio.docker.addon] Can't build cb7b3237/armv7-addon-motion:0.5.20: The command '/bin/ash -o pipefail -c apk add --no-cache   apache2   apache2-utils   bc   coreutils   curl   dateutils   findutils   ffmpeg@edge   motion@edge   gawk   imagemagick   inotify-tools   jq   mosquitto-clients   python3   tcsh   git' returned a non-zero code: 99
`

**Comment by dcmartin** [comment]
I have completed rebuilding the system; if you would like to test, LMK.
