### ISSUE TITLE
Failed to save addon configuration

### ISSUE THREAD

**Issue by IrealiTY** [dcmartin/hassio-addons#5]
No matter what config I try to enter for the `motion-video0` addon, I receive the following error:
`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {}`
There I tried an empty config, but it seems that no matter what I enter, it spits the same error:

```log
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'log_level': 'info', 'log_motion_level': 'info', 'log_motion_type': 'ALL', 'default': {'changes': 'on', 'event_gap': 30, 'framerate': 5, 'minimum_motion_frames': 25, 'post_pictures': 'best', 'text_scale': 2, 'threshold_percent': 2, 'width': 640, 'height': 480}, 'group': 'motion', 'device': 'hostname', 'client': 'hostname', 'timezone': 'Europe/Berkin', 'cameras': [{'name': 'ps3eye', 'type': 'local'}]}
```

Component | Version
------------ | -------------
System | HassOS 4.12 on an Intel NUC
Supervisor | 234
Motion Video0 | 0.10.2

**Comment by XservicesOne** [comment]
Same problem....

**Comment by dcmartin** [comment]
Fixed
