### ISSUE TITLE
Installation for Rasa NLU failed

### ISSUE THREAD

**Issue by dj-bauer** [dcmartin/hassio-addons#6]
Thank you for your addon repo first. I was looking for a addon source for rasa.
My issue is, that the installation of rasa addon fails with
```20-09-12 14:15:28 ERROR (SyncWorker_3) [supervisor.docker.addon] Can't build cb7b3237/armv7-addon-rasa_nlu:0.1: The command '/bin/ash -o pipefail -c apk --no-cache --update-cache add gcc gfortran python python-dev py-pip build-base wget freetype-dev libpng-dev' returned a non-zero code: 2```

I think it is because python3 and python3-dev needs to become installed nowadays.
I tried to run the apk command in the terminal and trew an error.
It worked when I changed python to python3
I am using hassOS 4.12 and supervisor v.242 I hope I got all the necessary information gathered.

**Comment by dcmartin** [comment]
This addon is not-ready-for-primetime :-(
